DEFAULTS_CONNECTIVITY_YOU_ARE_NOT_CONNECTED_MSG = """\n\n

┏ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ┓
   CONNECTION ERROR !!!
┗━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━┛

YOU ARE NOT CONNECTED TO THE PREVIOUS INSTANCE. 

THIS PROGRAMM MIGHT STILL TRY TO CONNECT TO A LOCAL RAY INSTANCE FOR YOU. 
YOU SHOULD CHECK THE CONNECITVIY TO RAY UNTIL THIS MESSAGE GOES AWAY.
"""
DEFAULTS_STATEFUL_ACTOR_NAME="remote_stateful_actor"
