DEFAULTS_CONNECTIVITY_YOU_ARE_NOT_CONNECTED_MSG = """\n
┏ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ┓
   CONNECTION ERROR !!!
┗━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━ ━┛

YOU ARE NOT CONNECTED TO A PYMC SERVER INSTANCE. 

THIS PROGRAMM MIGHT STILL TRY TO CONNECT TO A LOCAL RAY INSTANCE FOR YOU. 
YOU SHOULD CHECK THE CONNECITVIY TO RAY UNTIL THIS MESSAGE GOES AWAY.

NOTE: 
----
YOU CAN DEFAULT TO A LOCAL INSTANCE BY SUPPLYING THE `allow_local_fallback=True` OPTION
ALL WORK DONE WITH THIS INSTANCE IS THEN ONLY EXECUTED LOCALY.
"""
DEFAULTS_CONNECTIVITY_ALREADY_CONNECTED_MSG="You connected. Skipping re-connect."
DEFAULTS_STATEFUL_ACTOR_NAME="remote_stateful_actor"
DEFEAULTS_RAY_DEBUG_ENV_VAR_NAME="RAY_DEBUG"
