resources:
  # Optional; if left out, automatically pick the cheapest cloud.
  cloud: azure
  # 1x NVIDIA V100 GPU
  accelerators: V200:2
  ports : 8000

workdir: ./src/pymc_server/workDir_test
pymc_yaml: ./src/pymc_server/pymc.yaml